<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colors [
 <!ELEMENT colors (color*)>
 <!ELEMENT color (nameSvg,code)+>
 <!ELEMENT code (rgb|cmyk)*>
 <!ELEMENT nameSvg (#PCDATA)>
 <!ELEMENT rgb (#PCDATA)>
 <!ELEMENT cmyk (#PCDATA)>
]>
<colors>
    <color>
        <nameSvg>Purple</nameSvg>
            <code>
            <rgb>#800080</rgb>
            </code>
    </color>
    <color>
        <nameSvg>Purple</nameSvg>
            <code>
            <cmyk>#00FF007F</cmyk>
            </code>
    </color>
</colors>